### ISSUE TITLE
Status of mirco / MATE with wayland

### ISSUE THREAD

**Issue by sunweaver** [wmww/mirco#3]
@wmww Hi! I wanted to check what the status of mirco is and if it is still thought to be the replacement of marco in MATE when running in Wayland mode. Will Mir still be a thing for marco? Any status update?

**Comment by wmww** [comment]
Aside from maintaining gtk-layer-shell (which some MATE projects use), I'm not actively involved with the MATE project. Canonical was having me work on MATE-related stuff, but that winded down a few years ago and now I've also left Canonical. They're welcome to use the code that's here, but you have to ask them what their plans are.

**Comment by sunweaver** [comment]
Thanks for the feedback.
